---
:replay_settings:
  :vcr_cassette_path: spec/support/vcr_cassettes
  :internal_cassette: complex_interactions/dslogon_flow/internal_interactions
  :external_cassette: complex_interactions/dslogon_flow/external_interactions
  :insecure_random: true
  :time_freeze: true
